# Netlify Configuration for Hiligaynon Vocabulary App
# This file optimizes deployment and performance

[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite builds to 'dist')
  publish = "dist"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers for educational app
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Enable CORS for AWS Polly (if needed)
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Cache optimization for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache optimization for audio files (if any local audio)
[[headers]]
  for = "/*.mp3"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.wav"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Optimize images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Environment variable examples (set these in Netlify dashboard)
# VITE_AWS_ACCESS_KEY_ID = "your_aws_access_key"
# VITE_AWS_SECRET_ACCESS_KEY = "your_aws_secret_key"  
# VITE_AWS_REGION = "ap-southeast-1"

# Build plugins for optimization
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Form handling (if you add contact forms later)
# [[forms]]
#   name = "contact"